pipeline:

  my-build:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t jph-hello-world .
      - docker login -u="jphardy" -p=${DOCKER_PASSWORD} quay.io
      - docker tag jph-hello-world quay.io/ukhomeofficedigital/jph-hello-world:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/jph-hello-world:${DRONE_COMMIT_SHA}    
    when:
      branch: master
      event: push

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
